### ISSUE TITLE
Latest fix for x86_64 brakes the build for gcc2

### ISSUE THREAD

**Issue by Begasus** [miqlas/W6#2]
sources/W6-bc2f91183e159804ef8ce3773bf562a132e1ebb7/sources/BubbleHelper.cpp:47: passing `int (*)(void *)' as argument 1 of `spawn_thread(status_t (*)(void *), const char *, long int, void *)'

**Comment by korli** [comment]
fixed in b1940f137e20efee91c0ae060509b7b8507a9159
